"""Verification: compile a candidate formalisation and check what it commits to.

The reason this project targets a proof assistant rather than a schema is that
a type checker can enforce things a schema cannot.  Three checks run here, in
increasing order of interest:

1. **It compiles.**  The candidate is well-typed Lean: the factors exist, the
   remedy is a real remedy, the outcome is a real side.  This is the cheap
   check and it is what most autoformalisation work means by "verified".

2. **It is well-formed as a holding.**  `Holding.WellFormed` requires that
   every factor the ruling relies on is present in the fact situation *and
   favours the party who won*.  This catches a specific and common failure: a
   model that reads "the ox was innocuous, therefore the owner pays only half"
   and records `behavedAnomalously` as a reason for the *claimant*.  It is a
   reasoning error, not a syntax error, and the compiler catches it.  (It
   caught exactly that mistake in our own hand-formalisation of Mishnah Bava
   Kamma 1:1 -- see the git history of `Nomos/Corpus/Rabbinic.lean`.)

3. **It coheres with the tradition.**  Adding the candidate to its own
   tradition's case base must not make that base force both outcomes on any
   situation it addresses.  A candidate that fails this is not necessarily
   wrong -- legal orders really do contradict themselves, and we proved that
   the Covenant Code does -- but it is a claim that needs defending, so the
   pipeline surfaces it rather than silently accepting it.

Check 3 is what makes this more than a syntax filter.  A model that formalises
a provision in a way that contradicts the twenty provisions already formalised
around it has almost certainly misread it, and no amount of type-checking the
provision in isolation would reveal that.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from typing import Optional

from .analogy import Holding

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LEAN_DIR = os.path.join(HERE, "lean")

TRADITION_CORPUS = {
    "covenant": "Nomos.Corpus.Covenant.corpus",
    "rabbinic": "Nomos.Corpus.Rabbinic.corpus",
    "roman": "Nomos.Corpus.Roman.corpus",
    "mesopotamian": "Nomos.Corpus.Mesopotamia.corpus",
}


@dataclass
class VerifyResult:
    compiles: bool
    well_formed: bool
    coheres: Optional[bool]          # None when no tradition corpus was given
    forces_outcome: Optional[str]    # what the existing corpus already forced
    is_novel: Optional[bool]         # True if the situation was open before
    errors: list[str] = field(default_factory=list)
    diagnostics: dict = field(default_factory=dict)
    source: str = ""

    @property
    def ok(self) -> bool:
        return self.compiles and self.well_formed

    def summary(self) -> str:
        bits = [
            f"compiles={self.compiles}",
            f"well_formed={self.well_formed}",
            f"coheres={self.coheres}",
            f"novel={self.is_novel}",
        ]
        if self.errors:
            bits.append(f"errors={len(self.errors)}")
        return " ".join(bits)


def lean_available() -> bool:
    return shutil.which("lake") is not None and os.path.isdir(LEAN_DIR)


def _factors_lean(names: list[str]) -> str:
    return "[" + ", ".join(f"Factor.{n}" for n in names) + "]"


def render(h: Holding, decl: str = "candidate") -> str:
    """Render a holding as a Lean `Precedent` declaration."""
    return (
        f"def {decl} : Precedent :=\n"
        f'  {{ cite := {json.dumps(h.cite)}\n'
        f"  , situation := ⟨{_factors_lean(h.situation)}⟩\n"
        f"  , winner := Side.{h.winner}\n"
        f"  , remedy := {h.remedy}\n"
        f"  , reason := {_factors_lean(h.reason)} }}\n"
    )


def render_check_file(h: Holding, tradition: str | None = None) -> str:
    base = TRADITION_CORPUS.get((tradition or h.tradition or "").lower())
    parts = [
        "-- generated by nomos.verify; do not edit",
        "import Nomos",
        "open Nomos",
        "",
        render(h),
        "",
        "-- (2) well-formedness: the ratio must consist of factors present in the",
        "--     case and favouring the winner.  A failure here is a reasoning",
        "--     error the type checker can see.",
        "example : candidate.WellFormed := by decide",
        "",
    ]
    if base:
        parts += [
            f"-- (3) coherence with {base}",
            f"abbrev base : Corpus := {base}",
            "abbrev extended : Corpus := Corpus.add base candidate",
            'def report : IO Unit := do',
            '  IO.println ("NOMOS_COHERES " ++ '
            'toString (decide (CoherentOn extended extended.situations)))',
            '  IO.println ("NOMOS_BASE_COHERES " ++ '
            'toString (decide (CoherentOn base base.situations)))',
            '  IO.println ("NOMOS_WAS_OPEN " ++ '
            'toString (decide (Open base candidate.situation)))',
            '  IO.println ("NOMOS_BASE_FORCED_CLAIMANT " ++ '
            'toString (decide (Forces base candidate.situation Side.claimant)))',
            '  IO.println ("NOMOS_BASE_FORCED_RESPONDENT " ++ '
            'toString (decide (Forces base candidate.situation Side.respondent)))',
            '  for (p, c) in extended.conflictsAt candidate.situation do',
            '    IO.println ("NOMOS_CONFLICT " ++ p.cite ++ " || " ++ c.cite)',
            "#eval report",
            "",
        ]
    else:
        parts += [
            'def report : IO Unit := IO.println "NOMOS_NO_BASE"',
            "#eval report",
            "",
        ]
    return "\n".join(parts)


_ERR = re.compile(r"^(.*?):(\d+):(\d+): error: (.*)$", re.MULTILINE)


def verify(h: Holding, tradition: str | None = None,
           timeout: int = 180) -> VerifyResult:
    """Compile and check one candidate holding."""
    if not lean_available():
        return VerifyResult(False, False, None, None, None,
                            ["lean/lake not available on PATH"])

    # Pre-check in Python so the common failure gets a good message without
    # paying for a compile.
    mal = h.malformation()

    src = render_check_file(h, tradition)
    with tempfile.TemporaryDirectory() as td:
        path = os.path.join(td, "Candidate.lean")
        with open(path, "w", encoding="utf8") as fh:
            fh.write(src)
        try:
            proc = subprocess.run(
                ["lake", "env", "lean", path],
                cwd=LEAN_DIR, capture_output=True, text=True, timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            return VerifyResult(False, False, None, None, None,
                                [f"lean timed out after {timeout}s"], source=src)

    out = (proc.stdout or "") + "\n" + (proc.stderr or "")
    errors = [m.group(4).strip() for m in _ERR.finditer(out)]
    compiles = proc.returncode == 0 and not errors

    well_formed = compiles and not mal
    if mal and not errors:
        errors.extend(mal)

    def flag(key: str) -> Optional[bool]:
        m = re.search(rf"^{key} (true|false)$", out, re.MULTILINE)
        return None if not m else m.group(1) == "true"

    coheres = flag("NOMOS_COHERES")
    was_open = flag("NOMOS_WAS_OPEN")
    fc, fr = flag("NOMOS_BASE_FORCED_CLAIMANT"), flag("NOMOS_BASE_FORCED_RESPONDENT")
    forced = None
    if fc and not fr:
        forced = "claimant"
    elif fr and not fc:
        forced = "respondent"
    elif fc and fr:
        forced = "both"

    conflicts = re.findall(r"^NOMOS_CONFLICT (.*?) \|\| (.*)$", out, re.MULTILINE)

    return VerifyResult(
        compiles=compiles,
        well_formed=well_formed,
        coheres=coheres,
        forces_outcome=forced,
        is_novel=was_open,
        errors=errors,
        diagnostics={
            "conflicts": [{"claimant": a, "respondent": b} for a, b in conflicts],
            "base_coheres": flag("NOMOS_BASE_COHERES"),
            "returncode": proc.returncode,
        },
        source=src,
    )


def verify_many(hs: list[Holding], tradition: str | None = None,
                timeout: int = 180) -> list[VerifyResult]:
    return [verify(h, tradition, timeout) for h in hs]


def build_library(timeout: int = 900) -> tuple[bool, str]:
    """Build the Lean library; the verifier needs the oleans present."""
    if not lean_available():
        return False, "lake not found"
    proc = subprocess.run(["lake", "build"], cwd=LEAN_DIR,
                          capture_output=True, text=True, timeout=timeout)
    return proc.returncode == 0, (proc.stdout or "") + (proc.stderr or "")


def export_seed(timeout: int = 300) -> list[Holding]:
    """Run the Lean exporter and read back the seed corpus."""
    proc = subprocess.run(["lake", "exe", "export-corpus"], cwd=LEAN_DIR,
                          capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr[:2000])
    out = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            out.append(Holding.from_json(json.loads(line)))
    return out
